# Generated by Django 5.0.6 on 2024-06-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSodexi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='temps_minimum',
            new_name='minimum',
        ),
    ]
