# Generated by Django 5.0.6 on 2024-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSodexi', '0002_rename_temps_minimum_tarif_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='destination',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='origine',
            field=models.CharField(max_length=3),
        ),
    ]
