# Generated by Django 5.0.6 on 2024-06-12 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSodexi', '0004_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
