# Generated by Django 5.0.6 on 2024-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSodexi', '0007_latacsvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
