# Generated by Django 5.0.6 on 2024-06-17 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSodexi', '0008_tarif_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
