from django.db import models
class Cyd(models.Model):
    code_app = models.CharField(max_length=5)
    code_carte = models.CharField(max_length=2)
    num_cpt_urn_collectif = models.CharField(max_length=9)
    iata_orig = models.CharField(max_length=5)
    iata_dest = models.CharField(max_length=5)
    code_cca = models.CharField(max_length=1)
    cie_lta = models.CharField(max_length=3)
    num_lta = models.CharField(max_length=8)
    code_double = models.CharField(max_length=1)
    date_emission = models.CharField(max_length=8)
    unite_poids = models.CharField(max_length=1)
    pd_brut = models.CharField(max_length=7)
    pd_taxable = models.CharField(max_length=7)
    typ = models.CharField(max_length=1)
    mnt_htfac = models.CharField(max_length=15)
    cf1 = models.CharField(max_length=3)
    mf1 = models.CharField(max_length=15)
    cf2 = models.CharField(max_length=3)
    mf2 = models.CharField(max_length=15)
    cf3 = models.CharField(max_length=3)
    mf3 = models.CharField(max_length=15)
    cf4 = models.CharField(max_length=3)
    mf4 = models.CharField(max_length=15)
    cf5 = models.CharField(max_length=3)
    mf5 = models.CharField(max_length=15)
    filler = models.CharField(max_length=1)
    cmf = models.CharField(max_length=15)
    monnaie_fac = models.CharField(max_length=3)
    nb_dec_fac = models.CharField(max_length=1)
    code_service = models.CharField(max_length=2)
    code_tva = models.CharField(max_length=1)
    mode_paiement = models.CharField(max_length=2)
    mnt_compt = models.CharField(max_length=15)
    monnaie_compt = models.CharField(max_length=3)
    nb_dec_compt = models.CharField(max_length=1)
    num_cpt_urn_individuel = models.CharField(max_length=7)
    n_facture_af = models.CharField(max_length=10)

class TXTFile(models.Model):
    file = models.FileField(upload_to='media/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name